# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            '<a href="/">Dr. Veena Gopinath</a>'
tagline:          'Dermatologist'
description:      'Dermatology &amp; Cosmetology'

url:              

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/veenagopinath/veenagopinath.github.io
