# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Veena
tagline:          'Dermatologist'
description:      'Specialist in Dermatology and Cosmetology (ത്വഗ്രോഗ വിദഗ്ധ)'
url:              

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/veenagopinath/veenagopinath.github.io
